package com.ritika.dowinnApp.fragment

import android.app.Activity
import android.content.Intent
import android.os.Bundle
import android.util.Log
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.Toast
import androidx.activity.result.ActivityResultLauncher
import androidx.activity.result.contract.ActivityResultContracts
import androidx.fragment.app.Fragment
import androidx.navigation.fragment.findNavController
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInAccount
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.google.android.gms.tasks.Task
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import com.ritika.dowinnApp.BuildConfig
import com.ritika.dowinnApp.R
import com.ritika.dowinnApp.databinding.FragmentWelcomeBinding

// IMPORTANT: Do NOT rely on BuildConfig.DEFAULT_WEB_CLIENT_ID here.
// Use R.string.default_web_client_id from your google-services.json configuration.

class WelcomeFragment : Fragment() {
    private val TAG = "WelcomeFragment"
    private var _binding: FragmentWelcomeBinding? = null
    private val binding get() = _binding!!

    // Initialize these as non-nullable after onCreate/onViewCreated
    private lateinit var googleSignInClient: GoogleSignInClient
    private lateinit var firebaseAuth: FirebaseAuth
    private lateinit var googleSignInLauncher: ActivityResultLauncher<Intent>

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // 1. Initialize Firebase Auth
        firebaseAuth = FirebaseAuth.getInstance()

        // 2. Register for Google Sign-In result
        googleSignInLauncher = registerForActivityResult(
            ActivityResultContracts.StartActivityForResult()
        ) { result ->
            if (result.resultCode == Activity.RESULT_OK) {
                val task = GoogleSignIn.getSignedInAccountFromIntent(result.data)
                handleSignInResult(task)
            } else {
                Log.e(TAG, "Google Sign-In cancelled or failed: Result Code ${result.resultCode}")
                showProgress(false)
                Log.e(TAG, "Full result: resultCode=${result.resultCode}, data=${result.data}")
                Toast.makeText(context, "Sign-in cancelled.", Toast.LENGTH_SHORT).show()
            }

        }
    }

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?,
    ): View {
        _binding = FragmentWelcomeBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        // 3. Configure Google Sign-In using R.string.default_web_client_id
        // The value is automatically included from your google-services.json.
        val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            // Use the string resource generated by google-services.json
            .requestIdToken(BuildConfig.DEFAULT_WEB_CLIENT_ID)
            .requestEmail()
            .build()

        googleSignInClient = GoogleSignIn.getClient(requireActivity(), gso)

        // Set up button click listeners
        binding.signInButton.setOnClickListener {
            signInWithGoogle()
        }

        // Initially hide progress
        showProgress(false)
    }

    private fun signInWithGoogle() {
        showProgress(true)
        val signInIntent = googleSignInClient.signInIntent
        googleSignInLauncher.launch(signInIntent)
    }

    private fun handleSignInResult(task: Task<GoogleSignInAccount>) {
        try {
            val account = task.getResult(ApiException::class.java)
            val idToken = account.idToken

            if (idToken == null) {
                Log.e(TAG, "Google ID Token is null. Check google-services.json and SHA keys.")
                Toast.makeText(context, "Sign-in failed: Missing ID Token.", Toast.LENGTH_LONG).show()
                showProgress(false)
                return
            }

            Log.d(TAG, "Google Sign-In successful. Attempting Firebase Auth.")
            firebaseAuthWithGoogle(idToken)
        } catch (e: ApiException) {
            // ApiException.getStatusCode() provides more detail
            Log.w(TAG, "Google sign in failed: Status Code ${e.statusCode}", e)
            showProgress(false)
            Toast.makeText(context, "Google sign in failed. Code: ${e.statusCode}", Toast.LENGTH_LONG).show()
        }
    }

    private fun firebaseAuthWithGoogle(idToken: String) {
        val credential = GoogleAuthProvider.getCredential(idToken, null)
        firebaseAuth.signInWithCredential(credential)
            .addOnCompleteListener(requireActivity()) { task ->
                showProgress(false)
                if (task.isSuccessful) {
                    val user = firebaseAuth.currentUser
                    Log.d(TAG, "Firebase Authentication successful. User: ${user?.uid}")

                    // You don't usually need the ID token immediately, but the logic is fine
                    user?.getIdToken(true)?.addOnCompleteListener { tokenTask ->
                        if (tokenTask.isSuccessful) {
                            val token = tokenTask.result?.token
                            Log.d(TAG, "Firebase ID Token successfully retrieved.")
                        } else {
                            Log.e(TAG, "Failed to get Firebase ID token", tokenTask.exception)
                        }
                    }

                    Toast.makeText(context, "Welcome ${user?.displayName}!", Toast.LENGTH_SHORT).show()
                    findNavController().navigate(R.id.action_welcomeFragment_to_sliderFragment)
                } else {
                    Log.w(TAG, "Firebase Authentication failed", task.exception)
                    Toast.makeText(context, "Authentication failed: ${task.exception?.message}", Toast.LENGTH_LONG).show()
                }
            }
    }

    private fun showProgress(show: Boolean) {
        binding.overlayLayout.visibility = if (show) View.VISIBLE else View.GONE
        binding.progressBar.visibility = if (show) View.VISIBLE else View.GONE
        binding.signInButton.isEnabled = !show
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }
}